[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore:codecs.open\(\) is deprecated:DeprecationWarning:vaderSentiment
    ignore:Using `httpx` with `starlette.testclient`:DeprecationWarning:fastapi.testclient
